#!/bin/bash

umask 022
test -d package || ( echo 'Wrong working directory.'; exit 1 )
test -d src || ( echo 'Wrong working directory.'; exit 1 )

if test -d /service
then
  echo '/service exists. I assume that svscan is already running.'
  exit 0
fi

echo 'Creating /service...'
mkdir /service

# If we are in an lxc container, set $container to skip inittab configuration
if grep -aq container=lxc /proc/1/environ 2> /dev/null
then
  container="lxc"
fi

if [ -r /etc/inittab ] && [ -z $container ]
then
  /command/setlock /etc/inittab package/run.inittab
else
  if [ -w /etc/rc.d/rc.local ]
  then
    rclocal=/etc/rc.d/rc.local
  else
    rclocal=/etc/rc.local
  fi
  /command/setlock $rclocal package/run.rclocal $rclocal
fi
