#!/bin/sh

umask 022
test -d package || ( echo 'Wrong working directory.'; exit 1 )
test -d src || ( echo 'Wrong working directory.'; exit 1 )

mkdir -p /command

# get the group with id=0 (root/wheel)
rootgrp=$(awk -F: '$3==0 {print $1; exit}' /etc/group)
grp=""
if [ -n "$rootgrp" ]; then
    grp="-g $rootgrp"
fi

for i in `cat package/commands`
do
  rm -f /command/$i'{new}'
  install -o root $grp -m 755 ./command/$i /command/$i'{new}'
  mv -f /command/$i'{new}' /command/$i
done

bindir=/usr/local/bin
echo "Making command links in $bindir..."
mkdir -p $bindir
for i in `cat package/commands`
do
  rm -f $bindir/$i'{new}'
  ln -s /command/$i $bindir/$i'{new}'
  mv -f $bindir/$i'{new}' $bindir/$i
done
